<?php

class PxlCircleSvg_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_circle_svg';
    protected $title = 'Circle SVG BR';
    protected $icon = 'eicon-library-upload';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_path","label":"Path Svg","tab":"style","controls":[{"name":"path_svg_text","label":"Path","type":"textarea","default":"<path opacity=\"0.5\" d=\"M-14.9456 461.346C48.5506 439.593 219.725 419.185 396.455 511.575C617.367 627.062 885.327 661.482 1047.16 455.635C1208.99 249.787 1219.85 132.538 1613.03 169.184C1695.21 175.915 1872.69 151.729 1925.22 1.13761\" stroke=\"#9F90FF\" stroke-width=\"3\"\/>"},{"name":"color_box_shadow","label":"Box Shadow Color","type":"color","selectors":{"{{WRAPPER}} .pxl-circle-svg svg":"filter: drop-shadow(0px 14px 10px {{VALUE}});"}},{"name":"bg_parallax_height","label":"SVG Height","type":"slider","control_type":"responsive","default":{"unit":"px"},"tablet_default":{"unit":"px"},"mobile_default":{"unit":"px"},"size_units":["px","vh"],"range":{"px":{"min":1,"max":1000},"vh":{"min":1,"max":100}}}]},{"name":"section_dot1","label":"Dot Left","tab":"style","controls":[{"name":"dot1_color_linear","label":"Dot Left Background Linear","type":"switcher","default":"true"},{"name":"dot1_color_one","label":"Dot Left Background Color One","type":"color","selectors":{"{{WRAPPER}} .pxl-circle-svg .linear-dot1 .stop1":"stop-color: {{VALUE}} !important;"},"condition":{"dot1_color_linear":"true"}},{"name":"dot1_color_two","label":"Dot Left Background Color Two","type":"color","selectors":{"{{WRAPPER}} .pxl-circle-svg .linear-dot1 .stop2":"stop-color: {{VALUE}} !important;"},"condition":{"dot1_color_linear":"true"}},{"name":"dot1_box_shadow","label":"Box Shadow","selectors":{"{{WRAPPER}} .pxl-circle-svg .filter1 feFlood":"flood-color: {{VALUE}} !important;"},"type":"color"}]},{"name":"section_dot2","label":"Dot Right","tab":"style","controls":[{"name":"dot2_color_linear","label":"Dot Right Background Linear","type":"switcher","default":"true"},{"name":"dot2_color_one","label":"Dot Right Background Color One","type":"color","selectors":{"{{WRAPPER}} .pxl-circle-svg .linear-dot2 .stop1":"stop-color: {{VALUE}} !important;"},"condition":{"dot2_color_linear":"true"}},{"name":"dot2_color_two","label":"Dot Right Background Color Two","type":"color","selectors":{"{{WRAPPER}} .pxl-circle-svg .linear-dot2 .stop2":"stop-color: {{VALUE}} !important;"},"condition":{"dot2_color_linear":"true"}},{"name":"dot2_box_shadow","label":"Box Shadow","selectors":{"{{WRAPPER}} .pxl-circle-svg .filter1 feFlood":"flood-color: {{VALUE}} !important;"},"type":"color"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}