<?php

defined("ABSPATH") || exit("No script kiddies please!");
reviews_goto_license();
echo "<form method=\"post\" action=\"options.php\" novalidate=\"novalidate\">\r\n    ";
settings_fields($this->_optionGroup);
wp_nonce_field("admin_devvn_reviews_nonce_action", "admin_devvn_reviews_nonce");
echo "    <table class=\"form-table\">\r\n        <tbody>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"img_size\">";
_e("Hình ảnh", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <p><label><input type=\"checkbox\" name=\"";
echo $this->_optionName;
echo "[disable_upload]\" value=\"1\" id=\"disable_upload\" ";
checked($devvn_review_settings["disable_upload"], 1, true);
echo "> Không cho upload ảnh khi đánh giá</label></p>\r\n                <p><input type=\"number\" value=\"";
echo $devvn_review_settings["img_size"];
echo "\" id=\"img_size\" name=\"";
echo $this->_optionName;
echo "[img_size]\"> byte<br>\r\n                    <small>Dung lượng của hình ảnh được phép up lên. Đơn vị byte. Mặc định là 512000byte ~ 500kb (1kb ~ 1024byte)</small></p>\r\n                Cho phép <input type=\"number\" min=\"1\" value=\"";
echo $devvn_review_settings["number_img_upload"];
echo "\" id=\"number_img_upload\" name=\"";
echo $this->_optionName;
echo "[number_img_upload]\"> hình ảnh được phép tải lên.\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"cmt_length\">";
_e("Độ dài nội dung tối thiểu", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <input type=\"number\" value=\"";
echo $devvn_review_settings["cmt_length"];
echo "\" id=\"cmt_length\" name=\"";
echo $this->_optionName;
echo "[cmt_length]\"> ký tự<br>\r\n                <small>Số ký tự tối thiểu trong nội dung. Không tính dấu cách. Mặc định 10 ký tự</small>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"review_position\">";
_e("Vị trí hiển thị", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                ";
$hook = apply_filters("devvn_reviews_position", ["woocommerce_after_single_product_summary", "woocommerce_after_single_product"]);
echo "                <select name=\"";
echo $this->_optionName;
echo "[review_position]\" id=\"review_position_select\">\r\n                    <option value=\"\">Mặc định</option>\r\n                    ";
foreach ($hook as $key) {
    echo "                        <option value=\"";
    echo $key;
    echo "\" ";
    selected($devvn_review_settings["review_position"], $key, true);
    echo ">";
    echo $key;
    echo "</option>\r\n                    ";
}
echo "                    <option value=\"custom\" ";
selected($devvn_review_settings["review_position"], "custom", true);
echo ">Tùy chỉnh</option>\r\n                </select>\r\n                <span class=\"review_position_action ";
echo $devvn_review_settings["review_position"] == "custom" ? "active" : "";
echo "\">Tên action <input type=\"text\" name=\"";
echo $this->_optionName;
echo "[review_position_action]\" value=\"";
echo $devvn_review_settings["review_position_action"];
echo "\" style=\"width: 200px\" id=\"review_position_action\"></span>\r\n                Vị trí ưu tiên <input type=\"number\" style=\"width: 50px\" value=\"";
echo $devvn_review_settings["review_priority"];
echo "\" id=\"review_priority\" name=\"";
echo $this->_optionName;
echo "[review_priority]\"><br>\r\n                <small>- Nếu không chọn vị trí hook để hiển thị reviews thì plugin sẽ hiển thị tại vị trí mặc định của theme quy định.<br>\r\n                    - Nếu chọn vị trí plugin sẽ loại bỏ tab review trong Woocommerce Tab mặc định. Sau đó hiển thị review tại hook bạn chọn<br>\r\n                    - Nếu chọn \"tùy chỉnh\" plugin sẽ loại bỏ tab review trong Woocommerce Tab mặc định. và nếu bạn nhập vào ô \"Tên action\" thì sẽ tự hiển thị trong action bạn nhập. Nếu bạn không nhập thì hãy đặt comments_template() vào chỗ muốn hiển thị reviews.<br>\r\n                    - Thứ tự ưu tiên hiển thị. Số càng to thì càng đứng sau. Mặc định 99</small>\r\n                </p>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"label_review\">";
_e("Tùy chỉnh label", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <input type=\"text\" value=\"";
echo $devvn_review_settings["label_review"];
echo "\" id=\"label_review\" name=\"";
echo $this->_optionName;
echo "[label_review]\"> <br/>\r\n                <small>Nếu bỏ trống thì các review đã mua hàng sẽ hiện <strong style=\"color: green;\">\"Đã mua hàng tại ";
echo $_SERVER["SERVER_NAME"];
echo "\"</strong></small>\r\n            </td>\r\n        </tr>\r\n        </tbody>\r\n    </table>\r\n    <table class=\"form-table\">\r\n        <tbody>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"show_date\">";
_e("Ẩn/Hiện ngày đánh giá", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_date]\" value=\"1\" ";
checked($devvn_review_settings["show_date"], 1, true);
echo "> Hiện</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_date]\" value=\"2\" ";
checked($devvn_review_settings["show_date"], 2, true);
echo "> Ẩn</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"show_like\">";
_e("Ẩn/Hiện nút thích", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_like]\" value=\"1\" ";
checked($devvn_review_settings["show_like"], 1, true);
echo "> Hiện</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_like]\" value=\"2\" ";
checked($devvn_review_settings["show_like"], 2, true);
echo "> Ẩn</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"show_avatar_review\">";
_e("Show/Hide avatar", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_avatar_review]\" value=\"1\" ";
checked($devvn_review_settings["show_avatar_review"], 1, true);
echo "> Hiện</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_avatar_review]\" value=\"2\" ";
checked($devvn_review_settings["show_avatar_review"], 2, true);
echo "> Ẩn</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"show_sold\">";
_e("Show/Hide sold count", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_sold]\" value=\"1\" ";
checked($devvn_review_settings["show_sold"], 1, true);
echo "> Hiện</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_sold]\" value=\"2\" ";
checked($devvn_review_settings["show_sold"], 2, true);
echo "> Ẩn</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"active_name_phone\">";
_e("Hiển thị sđt bên cạnh tên", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[active_name_phone]\" value=\"1\" ";
checked($devvn_review_settings["active_name_phone"], 1, true);
echo "> Có</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[active_name_phone]\" value=\"2\" ";
checked($devvn_review_settings["active_name_phone"], 2, true);
echo "> Không</label>\r\n                <br><small>Số điện thoại sẽ hiển thị dạng khuyết số bằng dấu *. Ví dụ 0912345***</small>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"hidden_phone_reviews\">";
_e("Ẩn SĐT trong phần reviews", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[hidden_phone_reviews]\" value=\"1\" ";
checked($devvn_review_settings["hidden_phone_reviews"], 1, true);
echo "> Ẩn</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[hidden_phone_reviews]\" value=\"2\" ";
checked($devvn_review_settings["hidden_phone_reviews"], 2, true);
echo "> Hiện</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"hidden_phone_reviews\">";
_e("Review style", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[rv_style]\" value=\"devvn-style\" ";
checked($devvn_review_settings["rv_style"], "devvn-style", true);
echo "> Kiểu 1 - Mặc định</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[rv_style]\" value=\"devvn-style2\" ";
checked($devvn_review_settings["rv_style"], "devvn-style2", true);
echo "> Kiểu 2 - Đóng khung</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"hidden_phone_reviews\">";
_e("Custom Rating in Loop ", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[loop_rating]\" value=\"0\" ";
checked($devvn_review_settings["loop_rating"], 0, true);
echo "> Không</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[loop_rating]\" value=\"1\" ";
checked($devvn_review_settings["loop_rating"], 1, true);
echo "> Có</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label>";
_e("Show rating stars when there are no reviews", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[loop_rating_zero]\" value=\"0\" ";
checked($devvn_review_settings["loop_rating_zero"], 0, true);
echo "> ";
_e("No", "devvn-reviews");
echo "</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[loop_rating_zero]\" value=\"1\" ";
checked($devvn_review_settings["loop_rating_zero"], 1, true);
echo "> ";
_e("Yes", "devvn-reviews");
echo "</label>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label>";
_e("Đánh giá nhanh", "devvn-reviews");
echo " <span class=\"label_new\">";
_e("New", "devvn-reviews");
echo "</span></label></th>\r\n            <td>\r\n                <textarea id=\"quick_review\" name=\"";
echo $this->_optionName;
echo "[quick_review]\">";
echo esc_textarea($devvn_review_settings["quick_review"]);
echo "</textarea><br>\r\n                <small>Mỗi đánh giá nhanh trên một dòng</small>\r\n            </td>\r\n        </tr>\r\n\r\n        </tbody>\r\n    </table>\r\n    <h2>";
_e("Tùy chỉnh shortcode reviews", "devvn-reviews");
echo "</h2>\r\n    <div class=\"review_note\"><strong>Shortcode [devvn_list_reviews]</strong><br>\r\n        Trong đó bao gồm:<br>\r\n        number: Số reviews hiển thị. Mặc định 10<br>\r\n        has_img: Để là 1 nếu chỉ muốn hiển thị các reviews có ảnh. Mặc định 0<br>\r\n        post_id: ID của sản phẩm muốn lấy reviews<br>\r\n        pc_column: Số cột hiển thị trên PC<br>\r\n        tablet_column: Số cột hiển thị trên Tablet<br>\r\n        mobile_column: Số cột hiển thị trên Mobile<br>\r\n    </div>\r\n    <table class=\"form-table\">\r\n        <tbody>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"include_script_shortcode\">";
_e("Shortcode reviews", "devvn-reviews");
echo " </label></th>\r\n                <td>\r\n                    <p>\r\n                        <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[include_script_shortcode]\" value=\"0\" ";
checked($devvn_review_settings["include_script_shortcode"], 0, true);
echo "> Không</label>\r\n                        <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[include_script_shortcode]\" value=\"1\" ";
checked($devvn_review_settings["include_script_shortcode"], 1, true);
echo "> Có</label><br>\r\n                        <small>Chọn CÓ nếu bạn có sử dụng shortcode này trên website</small></p>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"disable_owl_slider\">";
_e("Chạy Slider hình ảnh trong review", "devvn-reviews");
echo " </label></th>\r\n                <td>\r\n                    <p>\r\n                        <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[disable_owl_slider]\" value=\"0\" ";
checked($devvn_review_settings["disable_owl_slider"], 0, true);
echo "> Có chạy slider</label>\r\n                        <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[disable_owl_slider]\" value=\"1\" ";
checked($devvn_review_settings["disable_owl_slider"], 1, true);
echo "> Không chạy slider</label><br>\r\n                        <small>Chọn \"CÓ\" để chạy slider khi review có nhiều ảnh</small></p>\r\n                    </p>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"enable_img_popup\">";
_e("Chạy Slider hình ảnh trong review", "devvn-reviews");
echo " </label></th>\r\n                <td>\r\n                    <p>\r\n                        <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_img_popup]\" value=\"0\" ";
checked($devvn_review_settings["enable_img_popup"], 0, true);
echo "> Không bật popup</label>\r\n                        <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_img_popup]\" value=\"1\" ";
checked($devvn_review_settings["enable_img_popup"], 1, true);
echo "> Có bật popup</label><br>\r\n                        <small>Chọn \"CÓ\" bật popup hình ảnh khi click vào</small></p>\r\n                    </p>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"shortcode_reviews_number\">";
_e("Tổng số bài viết trên 1 trang", "devvn-reviews");
echo " </label></th>\r\n                <td>\r\n                    <p>\r\n                        <input type=\"number\" style=\"width: 50px\" name=\"";
echo $this->_optionName;
echo "[shortcode_reviews_number]\" value=\"";
echo $devvn_review_settings["shortcode_reviews_number"];
echo "\" min=\"1\">\r\n                        <small>Đây là số reviews hiển thị trên 1 trang. Bạn có thể tùy chỉnh ở từng shortcode. Mặc định là 10</small>\r\n                    </p>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"enable_img_popup\">";
_e("Cố cột hiển thị", "devvn-reviews");
echo " </label></th>\r\n                <td>\r\n                    <p>\r\n                        <input type=\"number\" style=\"width: 50px\" name=\"";
echo $this->_optionName;
echo "[shortcode_pc_column]\" value=\"";
echo $devvn_review_settings["shortcode_pc_column"];
echo "\" min=\"1\" max=\"5\"> cột trên PC\r\n                        <input type=\"number\" style=\"width: 50px\" name=\"";
echo $this->_optionName;
echo "[shortcode_tablet_column]\" value=\"";
echo $devvn_review_settings["shortcode_tablet_column"];
echo "\" min=\"1\" max=\"5\"> cột trên Tablet\r\n                        <input type=\"number\" style=\"width: 50px\" name=\"";
echo $this->_optionName;
echo "[shortcode_mobile_column]\" value=\"";
echo $devvn_review_settings["shortcode_mobile_column"];
echo "\" min=\"1\" max=\"5\"> cột trên Mobile<br>\r\n                        <small>Đây là số cột hiển thị mặc định. Bạn có thể tùy chỉnh ở từng shortcode. Max 5, min 1</small>\r\n                    </p>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"include_script_shortcode\">";
_e("Show product info in list", "devvn-reviews");
echo " </label></th>\r\n                <td>\r\n                    <p>\r\n                        <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[view_product_info_in_list]\" value=\"0\" ";
checked($devvn_review_settings["view_product_info_in_list"], 0, true);
echo "> Không</label>\r\n                        <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[view_product_info_in_list]\" value=\"1\" ";
checked($devvn_review_settings["view_product_info_in_list"], 1, true);
echo "> Có</label><br>\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n\r\n    <h2>";
_e("Tùy chỉnh phần bình luận", "devvn-reviews");
echo "</h2>\r\n    <table class=\"form-table\">\r\n        <tbody>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"show_tcmt\">";
_e("Ẩn/Hiện bình luận", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_tcmt]\" value=\"1\" ";
checked($devvn_review_settings["show_tcmt"], 1, true);
echo "> Hiện</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[show_tcmt]\" value=\"2\" ";
checked($devvn_review_settings["show_tcmt"], 2, true);
echo "> Ẩn</label>\r\n                <br><small>Mặc định có 2 phần đánh giá và bình luận. Chức năng ẩn này sẽ ẩn đi phần bình luận</small>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"tcmt_number\">";
_e("Số bình luận trên 1 trang", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <input type=\"number\" value=\"";
echo $devvn_review_settings["tcmt_number"];
echo "\" id=\"tcmt_number\" name=\"";
echo $this->_optionName;
echo "[tcmt_number]\">\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"tcmt_phone\">";
_e("Yêu cầu nhập SĐT", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[tcmt_phone]\" value=\"1\" ";
checked($devvn_review_settings["tcmt_phone"], 1, true);
echo "> Có</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[tcmt_phone]\" value=\"2\" ";
checked($devvn_review_settings["tcmt_phone"], 2, true);
echo "> Không</label>\r\n\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"active_field_email\">";
_e("Hiện/Ẩn trường email", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[active_field_email]\" value=\"1\" ";
checked($devvn_review_settings["active_field_email"], 1, true);
echo "> Hiện</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[active_field_email]\" value=\"2\" ";
checked($devvn_review_settings["active_field_email"], 2, true);
echo "> Ẩn</label>\r\n\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"enable_qapage\">";
_e("Kích hoạt cấu trúc FAQPage ", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_qapage]\" value=\"1\" ";
checked($devvn_review_settings["enable_qapage"], 1, true);
echo "> Có</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_qapage]\" value=\"2\" ";
checked($devvn_review_settings["enable_qapage"], 2, true);
echo "> Không</label>\r\n\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"enable_cmt_avatar\">";
_e("Hiện avatar", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_cmt_avatar]\" value=\"1\" ";
checked($devvn_review_settings["enable_cmt_avatar"], 1, true);
echo "> Hiện avatar</label>\r\n                <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_cmt_avatar]\" value=\"2\" ";
checked($devvn_review_settings["enable_cmt_avatar"], 2, true);
echo "> Ẩn avatar</label>\r\n\r\n            </td>\r\n        </tr>\r\n        </tbody>\r\n    </table>\r\n    <h2>";
_e("Tùy chỉnh bình luận cho post", "devvn-reviews");
echo "</h2>\r\n    <table class=\"form-table\">\r\n        <tbody>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"enable_postcmt\">";
_e("Kích hoạt giao diện comment cho POST và PAGE", "devvn-reviews");
echo "</label></th>\r\n                <td>\r\n                    <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_postcmt]\" value=\"1\" ";
checked($devvn_review_settings["enable_postcmt"], 1, true);
echo "> Có</label>\r\n                    <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_postcmt]\" value=\"2\" ";
checked($devvn_review_settings["enable_postcmt"], 2, true);
echo "> Không</label><br>\r\n                    <small>Có thể thêm custom post type bằng cách dùng filter devvn_post_comment_template mặc định array('post','page')</small>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th scope=\"row\"><label for=\"enable_postcmt_phone\">";
_e("Bắt buộc nhập sđt", "devvn-reviews");
echo "</label></th>\r\n                <td>\r\n                    <label style=\"margin-right: 10px;\"><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_postcmt_phone]\" value=\"1\" ";
checked($devvn_review_settings["enable_postcmt_phone"], 1, true);
echo "> Có</label>\r\n                    <label><input type=\"radio\" name=\"";
echo $this->_optionName;
echo "[enable_postcmt_phone]\" value=\"2\" ";
checked($devvn_review_settings["enable_postcmt_phone"], 2, true);
echo "> Không</label><br>\r\n                </td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n    <h2>";
_e("Công cụ", "devvn-reviews");
echo "</h2>\r\n    <table class=\"form-table\">\r\n        <tbody>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"sync_reviews\">";
_e("Đồng bộ đánh giá", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <button type=\"button\" class=\"button sync_old_reviews\">Đồng bộ bình luận cũ</button><span class=\"mess\"></span><br>\r\n                <small>Chỉ sử dụng chức năng này khi trước đây admin có trả lời reviews của khách</small>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"fake_bought\">";
_e("Fake label khách đã mua hàng", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <button type=\"button\" class=\"button fake_reviews_bought\">Fake ngay</button><span class=\"mess\"></span><br>\r\n                <small>Chức năng này giúp bạn fake tất cả các review cấp 1 có nhãn <strong style=\"color: green;\">\"đã mua hàng tại ";
echo $_SERVER["SERVER_NAME"];
echo "\"</strong>. <br>\r\n                    <strong>Chú ý:</strong> Nếu website của bạn có người dùng đánh giá thật thì không nên dùng nha</small>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"open_comment_prod\">";
_e("Mở comment", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <button type=\"button\" class=\"button open_comment_prod\"> Mở comment cho toàn bộ sản phẩm</button><span class=\"mess\"></span><br>\r\n                <small>Có thể hiện tại tất cả sản phẩm đang ở trạng thái đóng comment. Hãy ấn nút bên trên để cho phép comment.</small>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th scope=\"row\"><label for=\"fake_sold\">";
_e("Fake số lượng đã bán", "devvn-reviews");
echo "</label></th>\r\n            <td>\r\n                <p>Fake <input type=\"number\" value=\"20\" id=\"fake_per_page\" style=\"width: 58px;\"> sản phẩm / 1 page. Tăng giảm số này tùy vào cấu hình server của bạn.</p>\r\n                <p>Fake theo x2, x3 hoặc x4 lần số lượng <strong>reviews</strong> <button type=\"button\" data-type=\"reviews\" class=\"button fake_sold_prod\"> Fake ngay</button></p>\r\n                Fake theo khoảng cho trước từ <input value=\"20\" type=\"number\" min=\"0\" id=\"fake_sold_from\"> đến <input type=\"number\" min=\"0\" value=\"100\" id=\"fake_sold_to\"> sản phẩm đã bán <button type=\"button\" data-type=\"range_from\" class=\"button fake_sold_prod\"> Fake ngay</button><br>\r\n                <small style=\"color: red\">(Chú ý mỗi lần fake số lượng đã bán sẽ + với số hiện có)</small><br>\r\n                <hr>\r\n                Reset số lượng đã bán của tất cả sản phẩm về 0 <button type=\"button\" class=\"button button-danger reset_sold\" style=\" vertical-align: middle; \"> Reset ngay</button>\r\n                <hr>\r\n                <span class=\"mess\" style=\"margin-left: 0\"></span>\r\n            </td>\r\n        </tr>\r\n        </tbody>\r\n    </table>\r\n    ";
do_settings_fields($this->_optionGroup, "default");
echo "    ";
do_settings_sections($this->_optionGroup, "default");
echo "    ";
submit_button();
echo "</form>";

?>